### ISSUE TITLE
Faute de frappe

### ISSUE THREAD

**Issue by Jayllyz** [sebsheep/int-to-fp-elm#1]
Il y a une petite erreur dans le fichier [`02-elm-html/README.md`](https://github.com/sebsheep/int-to-fp-elm/blob/8f1e01c2e454876fc7a073a59347f92c44043cf9/02-elm-html/README.md#l146), `un sale erreur` à la place de `une sale erreur`. (ligne 146)

**Comment by sebsheep** [comment]
Merci !
